# Files for typos
# Instruction:  https://github.com/marketplace/actions/typos-action#getting-started

[default.extend-identifiers]

[default.extend-words]
# Don't correct following words
nin="nin"
nd="np" # nd may be np (numpy)


[files]
extend-exclude = ["_typos.toml"]
