wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: huggingface
    huggingface_version: 4.26.0.dev0
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.9.7
    start_time: 1675183707
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      - 71
      2:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      - 71
      4: 3.9.7
      5: 0.12.21
      6: 4.26.0.dev0
      8:
      - 2
      - 3
      - 5
adam_beta1:
  desc: null
  value: 0.9
adam_beta2:
  desc: null
  value: 0.999
adam_epsilon:
  desc: null
  value: 1.0e-08
adam_weight_decay:
  desc: null
  value: 0.01
allow_tf32:
  desc: null
  value: false
center_crop:
  desc: null
  value: false
checkpointing_steps:
  desc: null
  value: 10000
dataloader_num_workers:
  desc: null
  value: 0
enable_xformers_memory_efficient_attention:
  desc: null
  value: true
gradient_accumulation_steps:
  desc: null
  value: 4
gradient_checkpointing:
  desc: null
  value: false
hub_model_id:
  desc: null
  value: null
hub_token:
  desc: null
  value: null
initializer_token:
  desc: null
  value: dog
learnable_property:
  desc: null
  value: object
learning_rate:
  desc: null
  value: 0.0004
local_rank:
  desc: null
  value: -1
logging_dir:
  desc: null
  value: logs
lr_scheduler:
  desc: null
  value: constant
lr_warmup_steps:
  desc: null
  value: 0
max_train_steps:
  desc: null
  value: 3000
mixed_precision:
  desc: null
  value: fp16
num_train_epochs:
  desc: null
  value: 20
num_validation_images:
  desc: null
  value: 4
only_save_embeds:
  desc: null
  value: false
output_dir:
  desc: null
  value: textual_inversion_frida
placeholder_token:
  desc: null
  value: <frida>
pretrained_model_name_or_path:
  desc: null
  value: CompVis/stable-diffusion-v1-4
push_to_hub:
  desc: null
  value: false
repeats:
  desc: null
  value: 100
report_to:
  desc: null
  value: wandb
resolution:
  desc: null
  value: 512
resume_from_checkpoint:
  desc: null
  value: null
revision:
  desc: null
  value: fp16
save_steps:
  desc: null
  value: 500
scale_lr:
  desc: null
  value: true
seed:
  desc: null
  value: null
tokenizer_name:
  desc: null
  value: null
train_batch_size:
  desc: null
  value: 1
train_data_dir:
  desc: null
  value: frida
validation_prompt:
  desc: null
  value: A photo of <frida>
validation_steps:
  desc: null
  value: 1
