wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.3
    framework: huggingface
    huggingface_version: 4.21.3
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.8.5
    start_time: 1664860733.086191
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 63
      - 71
      - 80
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 63
      - 71
      - 80
      3:
      - 16
      - 23
      4: 3.8.5
      5: 0.13.3
      6: 4.21.3
      8:
      - 2
      - 3
      - 5
adam_beta1:
  desc: null
  value: 0.9
adam_beta2:
  desc: null
  value: 0.999
adam_epsilon:
  desc: null
  value: 1.0e-08
adam_weight_decay:
  desc: null
  value: 0.01
center_crop:
  desc: null
  value: false
data_aug:
  desc: null
  value: false
gradient_accumulation_steps:
  desc: null
  value: 4
gradient_checkpointing:
  desc: null
  value: true
guess_initializer_token:
  desc: null
  value: false
hub_model_id:
  desc: null
  value: null
hub_token:
  desc: null
  value: null
initialize_rest_random:
  desc: null
  value: false
initializer_token:
  desc: null
  value: dog
learnable_property:
  desc: null
  value: object
learning_rate:
  desc: null
  value: 0.0005
local_rank:
  desc: null
  value: -1
log_frequency:
  desc: null
  value: 100
logging_dir:
  desc: null
  value: logs
lr_scheduler:
  desc: null
  value: constant
lr_warmup_steps:
  desc: null
  value: 0
max_train_steps:
  desc: null
  value: 3000
mixed_precision:
  desc: null
  value: fp16
num_train_epochs:
  desc: null
  value: 100
num_vec_per_token:
  desc: null
  value: 1
output_dir:
  desc: null
  value: textual_inversion_frida
placeholder_token:
  desc: null
  value: <frida>
pretrained_model_name_or_path:
  desc: null
  value: CompVis/stable-diffusion-v1-4
project_name:
  desc: null
  value: huggingface_textual_inv
push_to_hub:
  desc: null
  value: false
repeats:
  desc: null
  value: 100
resolution:
  desc: null
  value: 512
save_frequency:
  desc: null
  value: 500
scale_lr:
  desc: null
  value: true
seed:
  desc: null
  value: null
slice_div:
  desc: null
  value: 2
subject_noun:
  desc: null
  value: null
tokenizer_name:
  desc: null
  value: null
train_batch_size:
  desc: null
  value: 1
train_data_dir:
  desc: null
  value: frida
use_auth_token:
  desc: null
  value: true
