wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: huggingface
    huggingface_version: 4.25.1
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.10.8
    start_time: 1672089958.559369
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 71
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 71
      3:
      - 16
      - 23
      4: 3.10.8
      5: 0.13.7
      6: 4.25.1
      8:
      - 2
      - 3
      - 5
adam_beta1:
  desc: null
  value: 0.9
adam_beta2:
  desc: null
  value: 0.999
adam_epsilon:
  desc: null
  value: 1.0e-08
adam_weight_decay:
  desc: null
  value: 0.01
center_crop:
  desc: null
  value: false
checkpointing_steps:
  desc: null
  value: 100000
gradient_accumulation_steps:
  desc: null
  value: 4
guidance_scale:
  desc: null
  value: 7.5
hub_model_id:
  desc: null
  value: null
hub_token:
  desc: null
  value: null
initializer_token:
  desc: null
  value: dog
learnable_property:
  desc: null
  value: object
learning_rate:
  desc: null
  value: 0.0001
local_rank:
  desc: null
  value: -1
log_frequency:
  desc: null
  value: 1
logging_dir:
  desc: null
  value: logs
lr_scheduler:
  desc: null
  value: constant
lr_warmup_steps:
  desc: null
  value: 0
max_train_steps:
  desc: null
  value: 5000
mixed_precision:
  desc: null
  value: fp16
num_train_epochs:
  desc: null
  value: 100
only_save_embeds:
  desc: null
  value: false
output_dir:
  desc: null
  value: dog_model_outputs
placeholder_token:
  desc: null
  value: <frida>
pretrained_model_name_or_path:
  desc: null
  value: CompVis/stable-diffusion-v1-4
project_name:
  desc: null
  value: huggingface_textual_inv
push_to_hub:
  desc: null
  value: false
repeats:
  desc: null
  value: 100
resolution:
  desc: null
  value: 512
resume_from_checkpoint:
  desc: null
  value: null
revision:
  desc: null
  value: null
save_steps:
  desc: null
  value: 500
scale_lr:
  desc: null
  value: true
seed:
  desc: null
  value: null
tokenizer_name:
  desc: null
  value: null
train_batch_size:
  desc: null
  value: 1
train_data_dir:
  desc: null
  value: ./frida
