name: Benchmarking tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - ci-*

env:
  DIFFUSERS_IS_CI: yes
  HF_HOME: /mnt/cache
  OMP_NUM_THREADS: 8
  MKL_NUM_THREADS: 8
  PYTEST_TIMEOUT: 600
  RUN_SLOW: yes
  PIPELINE_USAGE_CUTOFF: 50000

jobs:
  torch_pipelines_cuda_benchmark_tests:
    name: Torch Core Pipelines CUDA Benchmarking Tests
    strategy:
      fail-fast: false
      max-parallel: 1
    runs-on: docker-gpu
    container:
      image: diffusers/diffusers-pytorch-cuda
      options: --shm-size "16gb" --ipc host -v /mnt/hf_cache:/mnt/cache/ --gpus 0
    steps:
      - name: Checkout diffusers
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: NVIDIA-SMI
        run: |
          nvidia-smi
      - name: Install dependencies
        run: |
          apt-get update && apt-get install libsndfile1-dev libgl1 -y
          python -m pip install -e .[quality,test]
          python -m pip install git+https://github.com/huggingface/accelerate.git
      - name: Environment
        run: |
          python utils/print_env.py
      - name: Stable Diffusion Benchmarking Tests
        run: |
          cd benchmarks && mkdir benchmark_outputs && \
            python benchmark_sd.py && \
            python benchmark_sd.py --batch_size 4 && \
            python benchmark_sd.py --run_compile && \
            python benchmark_sd.py --batch_size 4 --run_compile 

      - name: Test suite reports artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: benchmark_test_reports
          path: benchmark_outputs