
name: Rebase Upstream

on:
  schedule:
    - cron: '0 0 * * *' # This runs the job nightly at midnight UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  rebase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout private repository
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Add upstream repository
        run: git remote add upstream https://github.com/huggingface/diffusers.git

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Rebase onto upstream main
        run: git rebase upstream/main

      - name: Push changes to private main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin main --force

